# Worksheet: Tensor basics + Autograd

Covers **`01_tensor_basics.py`** and **`02_autograd_gradients.py`**.

**How to use**
- Run the imports cell once.
- For each question: read the markdown, **predict** shapes/values/grads, then write code in the next cell and run it.
- Use `print()` freely; add `assert` when you want stricter checks.

**Open in Jupyter / VS Code:** select this notebook’s kernel (your `practice` venv if you use one).

In [1]:
import torch
import numpy as np

## Question 1 — Creating tensors

**TASK**
1. Create `t` from the list `[1, 2, 3, 4]` with `torch.tensor(...)`.
2. Create `z` as zeros with shape `(2, 3)`.
3. Create `u` shape `(2, 3)` uniform in `[0, 1)` (`rand`).
4. Create `v` shape `(2, 3)` standard normal `N(0,1)` (`randn`).

Print each tensor and its `.shape`.

**PREDICT:** Will `t`, `z`, `u`, `v` have the same dtype by default?

In [ ]:
# YOUR CODE HERE
t= torch.tensor([1, 2, 3, 4])
print(t)
z= torch.zeros(2, 3)
print(z)
u= torch.rand(2, 3)
print(u)
v= torch.randn(2, 3)
print(v)



tensor([1, 2, 3, 4])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.6291, 0.6147, 0.1917],
        [0.9647, 0.7678, 0.6455]])
tensor([[ 2.0361,  1.1570, -0.0277],
        [ 1.5623, -0.5139, -0.2567]])


## Question 2 — Tensor properties

**TASK:** Let `x = torch.randn(3, 4, 5)`. Print `x.shape`, `x.size()`, `x.dim()`, `x.numel()`, `x.dtype`, `x.device`.

**PREDICT:** What is `numel()` in terms of 3, 4, and 5?

In [11]:
# YOUR CODE HERE
x= torch.randn(3, 4, 5)
print("Data type:", x.dtype)
print("Device:", x.device)

Data type: torch.float32
Device: cpu


## Question 3 — Basic ops & dot

**TASK:**
```text
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])
```
Compute and print element-wise `a * b` and `torch.dot(a, b)`.

**PREDICT:** What scalar should `torch.dot(a, b)` be? (by hand)

In [13]:
# YOUR CODE HERE
a= torch.tensor([1., 2., 3.])
b= torch.tensor([4., 5., 6.])
product= a*b
print("Product:", product)
dot= torch.dot(a, b)
print("Dot product:", dot)

Product: tensor([ 4., 10., 18.])
Dot product: tensor(32.)


## Question 4 — Reshaping (`view`, `-1`)

**TASK:** `x = torch.randn(12)`. Reshape to `(3, 4)` with `.view(3, 4)`, then to `(*, 2)` with `.view(-1, 2)`. Print shapes.

**OPTIONAL:** `x_t = x.view(3, 4).transpose(0, 1)` then try `x_t.view(12)` — what happens? Fix with `.reshape(12)` or `.contiguous().view(12)`.

In [27]:
# YOUR CODE HERE
x= torch.randn(12)
print("Original:", x)
reshaped= x.view(3,4)
print("Reshaped:", reshaped)
reshaped_2= x.view(-1,2)
print("Reshaped 2:", reshaped_2.transpose(0,1).contiguous().view(12))





Original: tensor([ 1.4299, -0.0541,  0.2609, -1.3436, -1.5136, -0.5630,  0.1096, -2.2508,
         1.3897, -0.1221, -1.1241, -0.0989])
Reshaped: tensor([[ 1.4299, -0.0541,  0.2609, -1.3436],
        [-1.5136, -0.5630,  0.1096, -2.2508],
        [ 1.3897, -0.1221, -1.1241, -0.0989]])
Reshaped 2: tensor([ 1.4299,  0.2609, -1.5136,  0.1096,  1.3897, -1.1241, -0.0541, -1.3436,
        -0.5630, -2.2508, -0.1221, -0.0989])


## Question 5 — Indexing & slicing

**TASK:** `x = torch.randn(3, 4)`. Extract and print:
- first row
- first column
- element at row 1, col 2
- bottom-right `2×2` (last 2 rows, last 2 cols)

**PREDICT:** Shape of first column? Of the `2×2` block?

In [ ]:
# YOUR CODE HERE
x= torch.randn(3, 4)
print("x:", x)
print("first row:", x[0])
print("first col:", x[:, 0])
print("element at row 1, col 2:", x[1, 2])
print("bottom right 2x2:", x[-2:, -2:])

print("shape of 1st col:", x[:, 0].shape)



x: tensor([[ 0.4287, -0.4082, -1.1349, -0.9742],
        [-0.8468, -0.6724, -0.4100, -1.3250],
        [-0.5024,  0.9025,  0.2171,  0.2858]])
first row: tensor([ 0.4287, -0.4082, -1.1349, -0.9742])
first col: tensor([ 0.4287, -0.8468, -0.5024])
element at row 1, col 2: tensor(-0.4100)
bottom right 2x2: tensor([[-0.4100, -1.3250],
        [ 0.2171,  0.2858]])
shape of 1st col: torch.Size([3])


## Question 6 — Broadcasting

**TASK:** Like the tutorial: `a` shape `(3, 1)`, `b` shape `(1, 3)`, `result = a + b`. Print `result` and `result.shape`.

**PREDICT:** If `a[0,0]=1` and `b[0,1]=20`, what is `result[0, 1]`?

In [36]:
# YOUR CODE HERE
a= torch.randn(3, 1)
print("a:", a)
b= torch.randn(1, 3)
print("b:", b)
c=a+b
print("a+b", c)
print("a+b shape:", c.shape)

a: tensor([[-0.9130],
        [-0.4328],
        [ 0.6897]])
b: tensor([[ 0.2396, -2.0717, -0.9425]])
a+b tensor([[-0.6735, -2.9847, -1.8555],
        [-0.1932, -2.5044, -1.3753],
        [ 0.9293, -1.3819, -0.2528]])
a+b shape: torch.Size([3, 3])


## Question 7 — `cat` vs `stack`

**TASK:**
```text
x = torch.tensor([[1., 2.], [3., 4.]])
y = torch.tensor([[5., 6.], [7., 8.]])
```
Compute `c0 = torch.cat([x, y], dim=0)`, `c1 = torch.cat([x, y], dim=1)`, `s0 = torch.stack([x, y], dim=0)`. Print each and `.shape`.

**PREDICT:** Shapes of `c0`, `c1`, `s0`? In one sentence: how is stacking different from concatenating here?

In [ ]:
# YOUR CODE HERE
from tkinter import Y


x= torch.tensor([[1., 2.], [3., 4.]])
y= torch.tensor([[5., 6.], [7., 8.]])

c0= torch.cat([x, y], dim=1)
print("c0:", c0)
s0_0= torch.stack([x, y], dim=0) 
print("s0 stacked dim 0:", s0_0)

#for each row, you get a row from x and a row from y
s0_1= torch.stack([x, y], dim=1) 
print("s0 stacked dim 1:", s0_1)

#for each col, you get a col from x and a col from y
s0_2= torch.stack([x, y], dim=2) 
print("s0 stacked dim 2:", s0_2)

#stack inserts a new axis at position dim and stacks x and y along that axis
#cat makes it one long vector
# c0=[2,2] c1=[2,2] s0=[2,2,2]

c0: tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
s0 stacked dim 0: tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
s0 stacked dim 1: tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])
s0 stacked dim 2: tensor([[[1., 5.],
         [2., 6.]],

        [[3., 7.],
         [4., 8.]]])


## Question 8 — Scalar autograd

**TASK:**
```text
x = torch.tensor([3.0], requires_grad=True)
y = torch.tensor([2.0], requires_grad=True)
z = x * y + x ** 2
```
Run `z.backward()` and print `x.grad` and `y.grad`.

**PREDICT:** `dz/dx` = ? , `dz/dy` = ? (calculus)

In [ ]:
# YOUR CODE HERE
x= torch.tensor([3.0], requires_grad= True)
y= torch.tensor([2.0], requires_grad= True)
z= x* y+x **2
z.backward()
print("dz/dx:", x.grad) #predict its 8
print("dz/dy:", y.grad) #predict its 3

dz/dx: tensor([8.])
dz/dy: tensor([3.])


## Question 9 — Vector output & `backward`

**TASK:** `x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)`, `y = x ** 2`. **Without** `y.backward(torch.tensor([1.,1.,1.]))`, get the same `x.grad` by reducing `y` to a scalar first, then `.backward()`. Print `x.grad` (should match `2 * x` element-wise).

**PREDICT:** Why does `backward()` need a scalar (or an explicit gradient argument)?

In [ ]:
# YOUR CODE HERE
x= torch.tensor([1.0, 2.0, 3.0], requires_grad= True)
y= x**2
y.sum().backward() #use sum when you're plugging in a vector into a derivative
print("dy/dx", x.grad)

dy/dx tensor([2., 4., 6.])


## Question 10 — Matrix mean gradient + NumPy bridge

**TASK (autograd):** `x = torch.ones(2, 2) * 2.0` with `requires_grad=True`. `z = (x ** 2).mean()`. Print `z` (predict `4.0`). `z.backward()`; print `x.grad`. **PREDICT:** every `x.grad[i,j]` = ?

**TASK (NumPy):** `arr = np.array([1., 2., 3., 4.])`, `torch.from_numpy(arr)`, print tensor. Change `arr[0]` in NumPy; print tensor again (shared memory).

In [67]:
# YOUR CODE HERE

import torch
import numpy as np


x= torch.full((2, 2), 2.0, requires_grad= True)
print(x)
z= (x**2).mean()
print(z.item())
z.backward()
print("dy/dx:", x.grad)

arr= np.array([1., 2., 3., 4.])
print("tensor", torch.from_numpy(arr))
arr[0]= 6
print("tensor_changed", torch.from_numpy(arr))

tensor([[2., 2.],
        [2., 2.]], requires_grad=True)
4.0
dy/dx: tensor([[1., 1.],
        [1., 1.]])
tensor tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor_changed tensor([6., 2., 3., 4.], dtype=torch.float64)
