# Worksheet: Tensor basics + Autograd

Covers **`01_tensor_basics.py`** and **`02_autograd_gradients.py`**.

**How to use**
- Run the imports cell once.
- For each question: read the markdown, **predict** shapes/values/grads, then write code in the next cell and run it.
- Use `print()` freely; add `assert` when you want stricter checks.

**Open in Jupyter / VS Code:** select this notebook’s kernel (your `practice` venv if you use one).

In [1]:
import torch
import numpy as np

## Question 1 — Creating tensors

**TASK**
1. Create `t` from the list `[1, 2, 3, 4]` with `torch.tensor(...)`.
2. Create `z` as zeros with shape `(2, 3)`.
3. Create `u` shape `(2, 3)` uniform in `[0, 1)` (`rand`).
4. Create `v` shape `(2, 3)` standard normal `N(0,1)` (`randn`).

Print each tensor and its `.shape`.

**PREDICT:** Will `t`, `z`, `u`, `v` have the same dtype by default?

In [ ]:
# YOUR CODE HERE
t= torch.tensor([1, 2, 3, 4])
print(t)
z= torch.zeros(2, 3)
print(z)
u= torch.rand(2, 3)
print(u)
v= torch.randn(2, 3)
print(v)



tensor([1, 2, 3, 4])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.6291, 0.6147, 0.1917],
        [0.9647, 0.7678, 0.6455]])
tensor([[ 2.0361,  1.1570, -0.0277],
        [ 1.5623, -0.5139, -0.2567]])


## Question 2 — Tensor properties

**TASK:** Let `x = torch.randn(3, 4, 5)`. Print `x.shape`, `x.size()`, `x.dim()`, `x.numel()`, `x.dtype`, `x.device`.

**PREDICT:** What is `numel()` in terms of 3, 4, and 5?

In [11]:
# YOUR CODE HERE
x= torch.randn(3, 4, 5)
print("Data type:", x.dtype)
print("Device:", x.device)

Data type: torch.float32
Device: cpu


## Question 3 — Basic ops & dot

**TASK:**
```text
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])
```
Compute and print element-wise `a * b` and `torch.dot(a, b)`.

**PREDICT:** What scalar should `torch.dot(a, b)` be? (by hand)

In [13]:
# YOUR CODE HERE
a= torch.tensor([1., 2., 3.])
b= torch.tensor([4., 5., 6.])
product= a*b
print("Product:", product)
dot= torch.dot(a, b)
print("Dot product:", dot)

Product: tensor([ 4., 10., 18.])
Dot product: tensor(32.)


## Question 4 — Reshaping (`view`, `-1`)

**TASK:** `x = torch.randn(12)`. Reshape to `(3, 4)` with `.view(3, 4)`, then to `(*, 2)` with `.view(-1, 2)`. Print shapes.

**OPTIONAL:** `x_t = x.view(3, 4).transpose(0, 1)` then try `x_t.view(12)` — what happens? Fix with `.reshape(12)` or `.contiguous().view(12)`.

In [22]:
# YOUR CODE HERE
x= torch.randn(12)
print("Original:", x)
reshaped= x.view(3,4)
print("Reshaped:", reshaped)
reshaped_2= x.view(-1,2)
print("Reshaped 2:", reshaped_2.shape)

print("Transposed:",reshaped_2.transpose(0,1)) #swap dimension 0 and 1


y=torch.rand(3, 1, 3)
print("y:", y)


Original: tensor([ 1.0423, -1.1727, -0.8733,  1.4180, -0.3892, -1.9607,  1.0743,  0.7131,
         0.5148, -0.3828, -1.0371, -0.0107])
Reshaped: tensor([[ 1.0423, -1.1727, -0.8733,  1.4180],
        [-0.3892, -1.9607,  1.0743,  0.7131],
        [ 0.5148, -0.3828, -1.0371, -0.0107]])
Reshaped 2: torch.Size([6, 2])
Transposed: tensor([[ 1.0423, -0.8733, -0.3892,  1.0743,  0.5148, -1.0371],
        [-1.1727,  1.4180, -1.9607,  0.7131, -0.3828, -0.0107]])
y: tensor([[[0.2464, 0.5476, 0.4369]],

        [[0.4148, 0.3516, 0.5989]],

        [[0.7997, 0.4442, 0.9197]]])


## Question 5 — Indexing & slicing

**TASK:** `x = torch.randn(3, 4)`. Extract and print:
- first row
- first column
- element at row 1, col 2
- bottom-right `2×2` (last 2 rows, last 2 cols)

**PREDICT:** Shape of first column? Of the `2×2` block?

In [ ]:
# YOUR CODE HERE
pass

## Question 6 — Broadcasting

**TASK:** Like the tutorial: `a` shape `(3, 1)`, `b` shape `(1, 3)`, `result = a + b`. Print `result` and `result.shape`.

**PREDICT:** If `a[0,0]=1` and `b[0,1]=20`, what is `result[0, 1]`?

In [ ]:
# YOUR CODE HERE
pass

## Question 7 — `cat` vs `stack`

**TASK:**
```text
x = torch.tensor([[1., 2.], [3., 4.]])
y = torch.tensor([[5., 6.], [7., 8.]])
```
Compute `c0 = torch.cat([x, y], dim=0)`, `c1 = torch.cat([x, y], dim=1)`, `s0 = torch.stack([x, y], dim=0)`. Print each and `.shape`.

**PREDICT:** Shapes of `c0`, `c1`, `s0`? In one sentence: how is stacking different from concatenating here?

In [ ]:
# YOUR CODE HERE
pass

## Question 8 — Scalar autograd

**TASK:**
```text
x = torch.tensor([3.0], requires_grad=True)
y = torch.tensor([2.0], requires_grad=True)
z = x * y + x ** 2
```
Run `z.backward()` and print `x.grad` and `y.grad`.

**PREDICT:** `dz/dx` = ? , `dz/dy` = ? (calculus)

In [ ]:
# YOUR CODE HERE
pass

## Question 9 — Vector output & `backward`

**TASK:** `x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)`, `y = x ** 2`. **Without** `y.backward(torch.tensor([1.,1.,1.]))`, get the same `x.grad` by reducing `y` to a scalar first, then `.backward()`. Print `x.grad` (should match `2 * x` element-wise).

**PREDICT:** Why does `backward()` need a scalar (or an explicit gradient argument)?

In [ ]:
# YOUR CODE HERE
pass

## Question 10 — Matrix mean gradient + NumPy bridge

**TASK (autograd):** `x = torch.ones(2, 2) * 2.0` with `requires_grad=True`. `z = (x ** 2).mean()`. Print `z` (predict `4.0`). `z.backward()`; print `x.grad`. **PREDICT:** every `x.grad[i,j]` = ?

**TASK (NumPy):** `arr = np.array([1., 2., 3., 4.])`, `torch.from_numpy(arr)`, print tensor. Change `arr[0]` in NumPy; print tensor again (shared memory).

In [ ]:
# YOUR CODE HERE
pass